name: Continuous Integration - Commits

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited]

jobs:
  ci:
    name: 'PR Title and Commit Linter'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 #this fetches more history so we can use commit lint

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: ./.commitlint

    - run: yarn --cwd .commitlint --ignore-scripts

    - name: Commit Linter
      run: yarn --cwd .commitlint commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
