name: Continuous Integration - Code

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    pull_request_target:
        branches: [master]

jobs:
    ci:
        name: 'Linting, Tests and Coverage'
        runs-on: ubuntu-latest

        # Logic from https://hugo.alliau.me/2021/05/04/migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets/#share-your-secrets-with-dependabot
        # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
        # Otherwise, clone it normally.
        if: |
            (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
            (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x
                  cache-dependency-path: |
                      ./yarn.lock
                      ./server/yarn.lock
                  registry-url: 'https://npm.pkg.github.com/'
                  scope: '@mappedin'

            - name: Checkout (User)
              if: ${{ github.event_name != 'pull_request_target' }}
              uses: actions/checkout@v2

            - name: Checkout (Dependabot)
              if: ${{ github.event_name == 'pull_request_target' }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Install dependencies
              run: yarn --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_READ }}

            - name: Run prettier
              run: yarn prettier:check

            - name: Run linter
              run: yarn lint

            - name: Run tests
              run: yarn test:ci:full

            - name: Check code coverage against master
              uses: mappedin/coverage-ratchet-action@v1
              with:
                azure_blob_storage_connection_string: ${{ secrets.AZURE_COV_STORAGE_STRING }}
                mode: 'CHECK'
